### ISSUE TITLE
Could not find a version that satisfies the requirement django.js-vinta

### ISSUE THREAD

**Issue by reywright** [vintasoftware/django-react-boilerplate#95] opened 2017-05-05 22:07 UTC
```
Downloading/unpacking django.js-vinta (from -r require
ments-to-freeze.txt (line 8))
  Could not find a version that satisfies the requirem
ent django.js-vinta (from -r requirements-to-freeze.tx
t (line 8)) (from versions: 0.8.2.dev2)
Cleaning up...
No distributions matching the version for django.js-vi
nta (from -r requirements-to-freeze.txt (line 8))
Storing debug log for failure in /Users/local/Library/
Logs/pip.log```

**Comment by aericson** [comment] 2017-05-11 20:06
Thanks for reporting this.

I just tried it in new virtualenv without a pip cache and it worked fine.
Couldn't reproduce this.

Do you have any custom pip configuration?
Any information do you think could help reproducing this.

**Comment by reywright** [comment] 2017-05-17 21:49
I didn't try making a new virtualenv... I should have known definitely. Would it make sense to add to the README? I'll try it with that change maybe later in the week.

**Comment by aericson** [comment] 2017-06-28 01:37
Closing this. Feel free to reopen.

**Closed by aericson** 2017-06-28 01:37 UTC
