### ISSUE TITLE
compile_install_requirements is detecting conda environment and throwing environment not found error.

### ISSUE THREAD

**Issue by swainsubrat** [vintasoftware/django-react-boilerplate#504] opened 2020-05-11 15:35 UTC
I'm running the entire boilerplate from an anaconda environment. But it is not detecting any environment. Is the feature is not present or this is an issue IDK. But I'm putting it inside feature request.
The error message is like this
```
(base) thunderclap@darwin:~/Import Error/import_error$ make compile_install_requirements 
Installing pip-tools...
export PIP_REQUIRE_VIRTUALENV=true; \
pip install pip-tools
ERROR: Could not find an activated virtualenv (required).
Makefile:41: recipe for target 'compile_install_requirements' failed
make: *** [compile_install_requirements] Error 3

```

**Comment by swainsubrat** [comment] 2020-05-12 05:01
Hello, Anybody respond here. I really need this. Please.

**Comment by vanessa** [comment] 2020-06-08 13:18
Duplicate of #509

**Closed by vanessa** 2020-06-08 13:18 UTC
